// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4UdWeQKAOP0e4j18idChSAirsMbCRfrA',
    appId: '1:893608436640:web:2fc384199876e254a3fac5',
    messagingSenderId: '893608436640',
    projectId: 'flutterauthen01',
    authDomain: 'flutterauthen01.firebaseapp.com',
    storageBucket: 'flutterauthen01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARIv-5zZHkXViTcxLnZa4K_c4_4GfRdR0',
    appId: '1:893608436640:android:da6a9499a3a07976a3fac5',
    messagingSenderId: '893608436640',
    projectId: 'flutterauthen01',
    storageBucket: 'flutterauthen01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6QXIWNzAt5i3CJahBc97TEV3chE_v7II',
    appId: '1:893608436640:ios:1b38d7c054ec0e70a3fac5',
    messagingSenderId: '893608436640',
    projectId: 'flutterauthen01',
    storageBucket: 'flutterauthen01.appspot.com',
    iosBundleId: 'com.example.firebasetest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6QXIWNzAt5i3CJahBc97TEV3chE_v7II',
    appId: '1:893608436640:ios:85fa777baaa40741a3fac5',
    messagingSenderId: '893608436640',
    projectId: 'flutterauthen01',
    storageBucket: 'flutterauthen01.appspot.com',
    iosBundleId: 'com.example.firebasetest.RunnerTests',
  );
}
